# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ICPR2024_TimeSeriesAnonymisation',
                'doc_host': 'https://TimHal.github.io',
                'git_url': 'https://github.com/TimHal/ICPR2024_TimeSeriesAnonymisation',
                'lib_path': 'ICPR2024_TimeSeriesAnonymisation'},
  'syms': { 'ICPR2024_TimeSeriesAnonymisation.core': { 'ICPR2024_TimeSeriesAnonymisation.core.foo': ( 'core.html#foo',
                                                                                                      'ICPR2024_TimeSeriesAnonymisation/core.py')}}}
