# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_autoencoder_training.ipynb.

# %% auto 0
__all__ = ['train_mbientlab']

# %% ../nbs/10_autoencoder_training.ipynb 6
def train_mbientlab(
        max_epochs: int = 100, # Maximum number of epochs, if termination criterion
        export_path: str = None, # Path where the trained model is to be stored. 
    ) -> (float, float): # Final validation acc and precision 
    
    assert 1 == 1
    
    return 0.0, 0.0
